
// 定义一个常量名库

const CHANGE_USER_STATE = 'CHANGE_USER_STATE'
const CHANGE_MENU_LIST = 'CHANGE_MENU_LIST'
const CHANGE_MEETING_ROOM_DATA = 'CHANGE_MEETING_ROOM_DATA'
export { CHANGE_USER_STATE, CHANGE_MENU_LIST, CHANGE_MEETING_ROOM_DATA }